import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PostProvider } from "@/context/PostContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PostProvider>
          <div>{children}</div>
        </PostProvider>
      </body>
    </html>
    // <html lang="en">
    //   <PostProvider>
    //     <div>{children}</div>
    //   </PostProvider>
    // </html>
  );
}
